import NavBar, { NavItems} from '@/components/navbar';
import '@/styles/global.css';

export const metadata = {
  title: 'Welcome to site',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const navItems: NavItems[] = [
    {
      name: 'Home',
      href: '/',
    },
    {
      name: 'Cake',
      href: '/cake',
    },
    {
      name: 'The Beatles',
      href: '/beatles',
    }
  ]

  return (
    <html>
      <body>
      <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
        <NavBar navItems={navItems} />
        <div className="flex-grow flex-1 p-6 md:p-12 overflow-y-auto">{children}</div>
      </div>
      </body>
    </html>
  );
}
